ALTER TABLE users ADD COLUMN IF NOT EXISTS balance REAL DEFAULT 0.0;

CREATE TABLE IF NOT EXISTS earnings_log (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    amount REAL NOT NULL,
    source TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE active_numbers ADD COLUMN IF NOT EXISTS payout_done BOOLEAN DEFAULT FALSE;


