name: Deploy Bot to RDP

on:
  push:
    branches:
      - for-now

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            C:\Users\Administrator\Desktop\bot\shark-bot\deploy.bat
            C:\Users\Administrator\Desktop\bot\shark-bot-2\deploy.bat