name: Deploy Go Bots

on:
  push:
    branches:
      - for-now

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH (password)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            echo "🚀 Deploying shark-bot..."
            cd /root/shark-bot
            git pull origin for-now
            go build -o bot2

            echo "🚀 Deploying shark-bot-2..."
            cd /root/shark-bot-2
            git pull origin for-now
            go build -o sharkbot2

            echo "🔁 Restarting services..."
            systemctl restart sharkbot
            systemctl restart sharkbot2

            echo "✅ Deployment done!"